name: Destroy cloud resources
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  APP_ENVIRONMENT: development
jobs:
  destroy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/tasks_api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install NPM dependencies
        run: npm install
      - name: Destroy
        run: serverless remove --stage development --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  destroy-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/tasks_ui
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install serverless-s3-sync
        run: npm install --include=dev serverless-s3-sync
      - name: Install NPM dependencies
        run: npm install
      - name: Destroy
        run: serverless remove --stage development --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

