name: UI deploy
on:
  push:
    paths:
      - 'services/tasks_ui/**'
      - '.github/workflows/ui.yml'

env:  # new
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  APP_ENVIRONMENT: development


jobs:
  deploy-development:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]
    defaults:
      run:
        working-directory: services/tasks_ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install serverless
        run: npm install -g serverless serverless-s3-sync
      - name: Install NPM dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: serverless deploy --stage development --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
